# Generated by Django 2.2.7 on 2021-09-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0002_auto_20210917_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
    ]
