# Generated by Django 2.2.7 on 2021-09-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0003_remove_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.TextField(default='₽', verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
