# Generated by Django 2.2.7 on 2021-09-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0005_auto_20210921_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_date',
            field=models.TextField(default=None, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
