# Generated by Django 2.2.7 on 2021-10-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0008_auto_20210929_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новое'), (2, 'Готово')], default=1, verbose_name='Статус задания'),
        ),
    ]
