# Generated by Django 2.2.7 on 2021-10-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0009_auto_20211001_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default='Задание', verbose_name='Название задания'),
        ),
    ]
